# NyaMineFeatures configuration file

player-list-title: '&2                     NyaMine Classic ^_^            '

prometheus-stats:
  mined-blocks-counters:
    - emerald_ore
    - diamond_ore
    - lapis_ore
    - redstone_ore
    - gold_ore
    - iron_ore
    - coal_ore
    - nether_quartz_ore
    - stone
    - netherrack
    - ancient_debris
    - netherite_block
    - nether_gold_ore
    - gilded_blackstone

minecart-speed:
  max-speed-multiplier-with-player-in: 4.0
