name: NyaMineFeatures
version: ${project.version}
description: Sweet features for NyaMine
authors: [Galaran]

api-version: "1.13"
depend: [Kotlin, Essentials]
softdepend: [PrometheusExporter]
main: me.galaran.nyamine.NyaMineFeatures

commands:
  nyaadmin:
    description: NyaMineFeatures admin command
    permission: nyamine.admin
    permission-message: You do not have permission
  chorus:
    description: Gives you return chorus
    permission: nyamine.chorus
    permission-message: You do not have permission
  infinityspawnegg:
    description: Gives you infinity spawn egg, placeable to spawner
    permission: nyamine.infinityspawnegg
    permission-message: You do not have permission
  playerinfo:
    description: Some player info
    permission: nyamine.playerinfo
    permission-message: You do not have permission
  tpregion:
    description: Teleports player to the center of region, stored in mca file
    permission: nyamine.tpregion
    permission-message: You do not have permission

permissions:
  # Command permissions
  nyamine.admin:
    default: op
  nyamine.chorus:
    default: op
  nyamine.infinityspawnegg:
    default: op
  nyamine.playerinfo:
    default: op
  nyamine.tpregion:
    default: op

  # Passive abilities
  nyamine.breakspawners:
    defaut: true
