name: NyaMineFeatures
version: ${project.version}
description: Sweet features for NyaMine
authors: [Galaran]

api-version: "1.13"
depend: [Kotlin, Essentials, PrometheusExporter]
main: me.galaran.nyamine.NyaMineFeatures

commands:
  nyaadmin:
    description: NyaMineFeatures admin command
    permission: nyamine.admin
    permission-message: You do not have permission
  chorus:
    description: Gives you return chorus
    permission: nyamine.chorus
    permission-message: You do not have permission
  playerinfo:
    description: Some player info
    permission: nyamine.playerinfo
    permission-message: You do not have permission

permissions:
  nyamine.admin:
    default: op
  nyaminechorus:
    default: op
  nyamine.playerinfo:
    default: op
